package com.argonathsystems.adapter.hytale.packet;

import com.hypixel.hytale.protocol.Packet;
import com.hypixel.hytale.protocol.packets.interaction.SyncInteractionChain;
import com.hypixel.hytale.protocol.packets.interaction.SyncInteractionChains;
import com.hypixel.hytale.server.core.io.adapter.PlayerPacketWatcher;
import com.hypixel.hytale.server.core.universe.PlayerRef;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.annotation.Nonnull;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Temporary debug packet watcher that logs ALL inbound packets for specific players.
 *
 * <p>This watcher is used to discover what packets are sent when specific keys are pressed.
 * In particular, it helps identify the exact packet/InteractionType generated by the W key
 * (AZERTY layout) which opens the native Utility Slot Selector.</p>
 *
 * <h2>Usage</h2>
 * <ol>
 *   <li>Register with {@code PacketAdapters.registerInbound(debugWatcher)}</li>
 *   <li>Call {@link #enableForPlayer(UUID)} to start logging for a specific player</li>
 *   <li>Press keys in-game and check server logs for packet details</li>
 *   <li>Call {@link #disableForPlayer(UUID)} when done</li>
 * </ol>
 *
 * <p><b>IMPORTANT:</b> This watcher is a {@link PlayerPacketWatcher} (observe-only), 
 * NOT a {@link com.hypixel.hytale.server.core.io.adapter.PlayerPacketFilter}. 
 * It does NOT block any packets.</p>
 *
 * @author Argonath Systems Team
 * @version 1.0.0
 * @since SM-UI-055 (Debug tool for packet discovery)
 */
public class DebugPacketWatcher implements PlayerPacketWatcher {

    private static final Logger LOGGER = LoggerFactory.getLogger(DebugPacketWatcher.class);

    /** Players for which debug logging is enabled */
    private final Set<UUID> debugPlayers = ConcurrentHashMap.newKeySet();

    /** Whether to log ALL packet types or only interaction-related ones */
    private volatile boolean verboseMode = false;

    public DebugPacketWatcher() {
        LOGGER.info("[DEBUG-WATCHER] DebugPacketWatcher initialized — use enableForPlayer(UUID) to start logging");
    }

    /**
     * Enable debug packet logging for a specific player.
     *
     * @param playerId The player UUID to watch
     */
    public void enableForPlayer(UUID playerId) {
        debugPlayers.add(playerId);
        LOGGER.info("[DEBUG-WATCHER] Enabled packet logging for player {}", playerId);
    }

    /**
     * Disable debug packet logging for a specific player.
     *
     * @param playerId The player UUID to stop watching
     */
    public void disableForPlayer(UUID playerId) {
        debugPlayers.remove(playerId);
        LOGGER.info("[DEBUG-WATCHER] Disabled packet logging for player {}", playerId);
    }

    /**
     * Enable or disable verbose mode (log ALL packets, not just interaction ones).
     *
     * @param verbose true for all packets, false for interaction-related only
     */
    public void setVerboseMode(boolean verbose) {
        this.verboseMode = verbose;
        LOGGER.info("[DEBUG-WATCHER] Verbose mode: {}", verbose);
    }

    /**
     * Check if any players are being watched.
     *
     * @return true if at least one player is enabled for debug logging
     */
    public boolean isActive() {
        return !debugPlayers.isEmpty();
    }

    @Override
    public void accept(@Nonnull PlayerRef playerRef, @Nonnull Packet packet) {
        UUID playerId = playerRef.getUuid();

        // Only log for players with debug enabled
        if (!debugPlayers.contains(playerId)) {
            return;
        }

        String packetClassName = packet.getClass().getSimpleName();

        // Always log SyncInteractionChains in detail — this is the most likely
        // packet for the W key / utility selector
        if (packet instanceof SyncInteractionChains syncPacket) {
            LOGGER.info("[DEBUG-WATCHER] Player {} | PACKET: SyncInteractionChains | updates: {}",
                    playerId, syncPacket.updates != null ? syncPacket.updates.length : 0);

            if (syncPacket.updates != null) {
                for (int i = 0; i < syncPacket.updates.length; i++) {
                    SyncInteractionChain chain = syncPacket.updates[i];
                    LOGGER.info("[DEBUG-WATCHER]   Chain[{}]: interactionType={}, activeHotbarSlot={}, initial={}, data={}",
                            i,
                            chain.interactionType,
                            chain.activeHotbarSlot,
                            chain.initial,
                            chain.data != null ? "targetSlot=" + chain.data.targetSlot : "null");
                }
            }
            return;
        }

        // For verbose mode, log ALL other packets; otherwise only log "interesting" ones
        if (verboseMode) {
            LOGGER.info("[DEBUG-WATCHER] Player {} | PACKET: {} (class: {})",
                    playerId, packetClassName, packet.getClass().getName());
        } else {
            // Log only packets likely related to the utility selector / window system
            String lowerName = packetClassName.toLowerCase();
            if (lowerName.contains("window") || lowerName.contains("open") ||
                    lowerName.contains("close") || lowerName.contains("interaction") ||
                    lowerName.contains("slot") || lowerName.contains("utility") ||
                    lowerName.contains("custom") || lowerName.contains("page") ||
                    lowerName.contains("input") || lowerName.contains("action")) {
                LOGGER.info("[DEBUG-WATCHER] Player {} | PACKET: {} (class: {})",
                        playerId, packetClassName, packet.getClass().getName());
            }
        }
    }

    /**
     * Clean up when a player disconnects.
     *
     * @param playerId The player who disconnected
     */
    public void onPlayerDisconnect(UUID playerId) {
        debugPlayers.remove(playerId);
    }
}
